max_width = 100
hard_tabs = false
tab_spaces = 4
reorder_imports = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
wrap_comments = true
trailing_comma = "Vertical"
use_field_init_shorthand = true
control_brace_style = "AlwaysSameLine"
brace_style = "SameLineWhere"
